IMAGE_WIDTH = 128
IMAGE_HEIGHT = 128

POPULATION_SIZE = 200
NUM_TRIANGLES = 80

TOURNAMENT_SIZE = 3

NUM_GENERATIONS = 3000
MUTATION_RATE = 0.30

DELTA_COORDENADA = 30
DELTA_COR = 30
DELTA_ALPHA = 12
ALPHA_MIN = 20
ALPHA_MAX = 120

TRIANGULO_PEQUENO_MIN = 3
TRIANGULO_PEQUENO_MAX = 15
TRIANGULO_MEDIO_MIN = 16
TRIANGULO_MEDIO_MAX = 35
TRIANGULO_GRANDE_MIN = 36
TRIANGULO_GRANDE_MAX = max(IMAGE_WIDTH, IMAGE_HEIGHT)

TARGET_IMAGE = "assets/alvo/alvo.png"
RESULTS_DIR = "assets/resultados"
